<?php

declare(strict_types=1);

namespace Database\Seeders\User;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    private array $permittedRoutes = [
//        "another_service.index",
//        "another_service.store",
//        "another_service.edit",
//        "another_service.update",
//        "another_service.delete",
//        "another_service.generate",
//        "arrival_time.index",
//        "arrival_time.store",
//        "arrival_time.edit",
//        "arrival_time.update",
//        "arrival_time.delete",
//        "logout",
//        "users.info",
//        "brand.index",
//        "brand.store",
//        "brand.edit",
//        "brand.update",
//        "brand.delete",
//        "category.index",
//        "category.store",
//        "category.edit",
//        "category.update",
//        "category.delete",
//        "client.index",
//        "client.store",
//        "client.edit",
//        "client.show",
//        "client.update",
//        "client.delete",
//        "client.generate",
//        "contract.index",
//        "contract.store",
//        "contract.edit",
//        "contract.show",
//        "contract.update",
//        "contract.delete",
//        "contract.fiz.files.main.contract.file",
//        "contract.fiz.files.annex.contract.file",
//        "contract.iur.files.main.contract.file",
//        "contract.iur.files.annex.contract.file",
//        "dashboard.index",
//        "executor.index",
//        "executor.store",
//        "executor.edit",
//        "executor.update",
//        "executor.delete",
//        "filial.index",
//        "filial.store",
//        "filial.edit",
//        "filial.show",
//        "filial.update",
//        "filial.delete",
//        "filial.transfer.store",
//        "filial.transfer.products.list",
//        "maintenance.index",
//        "maintenance.store",
//        "maintenance.edit",
//        "maintenance.update",
//        "maintenance.delete",
//        "maintenance.fiz.download",
//        "maintenance.iur.download",
//        "product.index",
//        "product.store",
//        "product.edit",
//        "product.update",
//        "product.delete",
//        "product.media.delete",
//        "security-type.index",
//        "security-type.store",
//        "security-type.edit",
//        "security-type.update",
//        "security-type.delete",
//        "template-file.index",
//        "template-file.update",
//        "subject.fiz.files.statement.subject.file",
//        "subject.fiz.files.security.type.work.subject.file",
//        "subject.fiz.files.act.exploitation.subject.file",
//        "subject.fiz.files.act_priema_v_explotatiu.subject.file",
//        "subject.fiz.files.plan_shema.subject.file",
//        "subject.fiz.files.instruction.subject.file",
//        "subject.fiz.files.instruction_trev.subject.file",
//        "subject.fiz.files.state_pult.subject.file",
//        "subject.fiz.files.material_people.subject.file",
//        "subject.fiz.files.arenda.subject.file",
//        "subject.fiz.files.montaj_service.subject.file",
//        "subject.iur.files.statement.subject.file",
//        "subject.iur.files.security.type.work.subject.file",
//        "subject.iur.files.act.exploitation.subject.file",
//        "subject.iur.files.act_priema_v_explotatiu.subject.file",
//        "subject.iur.files.plan_shema.subject.file",
//        "subject.iur.files.instruction.subject.file",
//        "subject.iur.files.instruction_trev.subject.file",
//        "subject.iur.files.state_pult.subject.file",
//        "subject.iur.files.material_people.subject.file",
//        "subject.iur.files.arenda.subject.file",
//        "subject.iur.files.montaj_service.subject.file",
//        "subject.index",
//        "subject.store",
//        "subject.edit",
//        "subject.show",
//        "subject.update",
//        "subject.delete",
//        "subject.media.delete",
//        "subject.products.list",
//        "subscribe.index",
//        "subscribe.generate",
//        "transaction.index",
//        "transaction.store",
//        "transaction.edit",
//        "transaction.update",
//        "transaction.delete",
//        "transaction.get-subject-data",
//        "transaction.calculate-subject-price",
//        "transaction.calculate-subject-price-edit",
//        "transaction.generate",
//        "transaction.reverse",
//        "transfer.index",
//        "transfer.store",
//        //"transfer.edit",
//        "transfer.show",
//        //"transfer.update",
//        "transfer.updateStatus",
//        "transfer.delete",
//        "transfer.products.list",
//
//        //API
//        'api.logout',
//        'api.subject.get',
//        'api.subject.pay',
    ];

    private array $userPermittedRoutes = [
//        'user.logout',
//        'user.dashboard',
//        'user.subject.show',
//        'user.subject.calculate',
//        'user.subject.register_sms_transaction',
//        'user.transaction.get',
//        'user.transaction.thank-you',
//        'user.transaction.index',
//        'user.transaction.show',
//        'user.transaction.generate',
//        'user.transaction.subscribe',
//        'user.transaction.thank-you',
//        'user.subject.register_recurrent_transaction',
//        'user.subscribe.show',
//        'user.subscribe.get',
//        'user.subscribe.destroy',
//        'user.subscribe.thank-you',
//        'user.subscribe.list',
//        'user.subscribe.generate',
//        'user.subscribe.index',
    ];

    public function run(): void
    {
        foreach ($this->permittedRoutes as $route) {
            Permission::query()->updateOrCreate([
                'name' => $route,
                'guard_name' => 'web',
            ]);
        }

        foreach ($this->userPermittedRoutes as $route) {
            Permission::query()->updateOrCreate([
                'name' => $route,
                'guard_name' => 'web',
            ]);
        }
    }
}
