date.timezone = "UTC"
memory_limit = -1
post_max_size = 100M
upload_max_filesize = 80M

;aditiona settings
max_input_vars = 10000
upload_max_filesize = 512M
max_execution_time = 600
max_input_time = 600
