on:
  push:
    branches:
      - master

  workflow_dispatch:
        

name: "[PROD] radop.md CD action"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Add .env file"
        shell: bash

        env:
          ENV_CONTENT: ${{ vars.dev_env }}
          VERSION: dev
        run: |
          echo "$ENV_CONTENT" > .env

      - name: "Login to Github Packages"
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.admin_login }}
          password: ${{ secrets.admin_token }}

      - name: "Build image and push to GitHub Packages"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/dev/Dockerfile
          tags: "docker.pkg.github.com/denisbocharov12/radop-app/api:prod"
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: "Add ssh key"
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.ssh_key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"

      - name: "Update services"
        shell: bash
        env:
          COMPOSE_FILE_PATH: ${{ vars.docker_compose_file_path }}
        run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@185.181.229.183 "docker pull docker.pkg.github.com/denisbocharov12/radop-app/api:prod && docker-compose -f ${COMPOSE_FILE_PATH} up -d"
